<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['number' => 1, 'name_ar' => 'الفاتحة', 'name_id' => 'Al-Fatihah', 'revelation_place' => 'Mekah', 'ayah_count' => 7],
            ['number' => 2, 'name_ar' => 'البقرة', 'name_id' => 'Al-Baqarah', 'revelation_place' => 'Madinah', 'ayah_count' => 286],
            ['number' => 3, 'name_ar' => 'آل عمران', 'name_id' => "Ali 'Imran", 'revelation_place' => 'Madinah', 'ayah_count' => 200],
            ['number' => 4, 'name_ar' => 'النساء', 'name_id' => 'An-Nisa', 'revelation_place' => 'Madinah', 'ayah_count' => 176],
            ['number' => 5, 'name_ar' => 'المائدة', 'name_id' => 'Al-Maidah', 'revelation_place' => 'Madinah', 'ayah_count' => 120],
            ['number' => 6, 'name_ar' => 'الأنعام', 'name_id' => "Al-An'am", 'revelation_place' => 'Mekah', 'ayah_count' => 165],
            ['number' => 7, 'name_ar' => 'الأعراف', 'name_id' => "Al-A'raf", 'revelation_place' => 'Mekah', 'ayah_count' => 206],
            ['number' => 8, 'name_ar' => 'الأنفال', 'name_id' => 'Al-Anfal', 'revelation_place' => 'Madinah', 'ayah_count' => 75],
            ['number' => 9, 'name_ar' => 'التوبة', 'name_id' => 'At-Taubah', 'revelation_place' => 'Madinah', 'ayah_count' => 129],
            ['number' => 10, 'name_ar' => 'يونس', 'name_id' => 'Yunus', 'revelation_place' => 'Mekah', 'ayah_count' => 109],
            ['number' => 11, 'name_ar' => 'هود', 'name_id' => 'Hud', 'revelation_place' => 'Mekah', 'ayah_count' => 123],
            ['number' => 12, 'name_ar' => 'يوسف', 'name_id' => 'Yusuf', 'revelation_place' => 'Mekah', 'ayah_count' => 111],
            ['number' => 13, 'name_ar' => 'الرعد', 'name_id' => "Ar-Ra'd", 'revelation_place' => 'Madinah', 'ayah_count' => 43],
            ['number' => 14, 'name_ar' => 'ابراهيم', 'name_id' => 'Ibrahim', 'revelation_place' => 'Mekah', 'ayah_count' => 52],
            ['number' => 15, 'name_ar' => 'الحجر', 'name_id' => 'Al-Hijr', 'revelation_place' => 'Mekah', 'ayah_count' => 99],
            ['number' => 16, 'name_ar' => 'النحل', 'name_id' => 'An-Nahl', 'revelation_place' => 'Mekah', 'ayah_count' => 128],
            ['number' => 17, 'name_ar' => 'الإسراء', 'name_id' => 'Al-Isra', 'revelation_place' => 'Mekah', 'ayah_count' => 111],
            ['number' => 18, 'name_ar' => 'الكهف', 'name_id' => 'Al-Kahfi', 'revelation_place' => 'Mekah', 'ayah_count' => 110],
            ['number' => 19, 'name_ar' => 'مريم', 'name_id' => 'Maryam', 'revelation_place' => 'Mekah', 'ayah_count' => 98],
            ['number' => 20, 'name_ar' => 'طه', 'name_id' => 'Tha-Ha', 'revelation_place' => 'Mekah', 'ayah_count' => 135],
            ['number' => 21, 'name_ar' => 'الأنبياء', 'name_id' => 'Al-Anbiya', 'revelation_place' => 'Mekah', 'ayah_count' => 112],
            ['number' => 22, 'name_ar' => 'الحج', 'name_id' => 'Al-Hajj', 'revelation_place' => 'Madinah', 'ayah_count' => 78],
            ['number' => 23, 'name_ar' => 'المؤمنون', 'name_id' => "Al-Mu'minun", 'revelation_place' => 'Mekah', 'ayah_count' => 118],
            ['number' => 24, 'name_ar' => 'النور', 'name_id' => 'An-Nur', 'revelation_place' => 'Madinah', 'ayah_count' => 64],
            ['number' => 25, 'name_ar' => 'الفرقان', 'name_id' => 'Al-Furqan', 'revelation_place' => 'Mekah', 'ayah_count' => 77],
            ['number' => 26, 'name_ar' => 'الشعراء', 'name_id' => "Asy-Syu'ara", 'revelation_place' => 'Mekah', 'ayah_count' => 227],
            ['number' => 27, 'name_ar' => 'النمل', 'name_id' => 'An-Naml', 'revelation_place' => 'Mekah', 'ayah_count' => 93],
            ['number' => 28, 'name_ar' => 'القصص', 'name_id' => 'Al-Qasas', 'revelation_place' => 'Mekah', 'ayah_count' => 88],
            ['number' => 29, 'name_ar' => 'العنكبوت', 'name_id' => "Al-'Ankabut", 'revelation_place' => 'Mekah', 'ayah_count' => 69],
            ['number' => 30, 'name_ar' => 'الروم', 'name_id' => 'Ar-Rum', 'revelation_place' => 'Mekah', 'ayah_count' => 60],
            ['number' => 31, 'name_ar' => 'لقمان', 'name_id' => 'Luqman', 'revelation_place' => 'Mekah', 'ayah_count' => 34],
            ['number' => 32, 'name_ar' => 'السجدة', 'name_id' => 'As-Sajdah', 'revelation_place' => 'Mekah', 'ayah_count' => 30],
            ['number' => 33, 'name_ar' => 'الأحزاب', 'name_id' => 'Al-Ahzab', 'revelation_place' => 'Madinah', 'ayah_count' => 73],
            ['number' => 34, 'name_ar' => 'سبإ', 'name_id' => "Saba'", 'revelation_place' => 'Mekah', 'ayah_count' => 54],
            ['number' => 35, 'name_ar' => 'فاطر', 'name_id' => 'Fatir', 'revelation_place' => 'Mekah', 'ayah_count' => 45],
            ['number' => 36, 'name_ar' => 'يس', 'name_id' => 'Yasin', 'revelation_place' => 'Mekah', 'ayah_count' => 83],
            ['number' => 37, 'name_ar' => 'الصافات', 'name_id' => 'As-Saffat', 'revelation_place' => 'Mekah', 'ayah_count' => 182],
            ['number' => 38, 'name_ar' => 'ص', 'name_id' => 'Sad', 'revelation_place' => 'Mekah', 'ayah_count' => 88],
            ['number' => 39, 'name_ar' => 'الزمر', 'name_id' => 'Az-Zumar', 'revelation_place' => 'Mekah', 'ayah_count' => 75],
            ['number' => 40, 'name_ar' => 'غافر', 'name_id' => 'Ghafir', 'revelation_place' => 'Mekah', 'ayah_count' => 85],
            ['number' => 41, 'name_ar' => 'فصلت', 'name_id' => 'Fussilat', 'revelation_place' => 'Mekah', 'ayah_count' => 54],
            ['number' => 42, 'name_ar' => 'الشورى', 'name_id' => 'Asy-Syura', 'revelation_place' => 'Mekah', 'ayah_count' => 53],
            ['number' => 43, 'name_ar' => 'الزخرف', 'name_id' => 'Az-Zukhruf', 'revelation_place' => 'Mekah', 'ayah_count' => 89],
            ['number' => 44, 'name_ar' => 'الدخان', 'name_id' => 'Ad-Dukhan', 'revelation_place' => 'Mekah', 'ayah_count' => 59],
            ['number' => 45, 'name_ar' => 'الجاثية', 'name_id' => 'Al-Jatsiyah', 'revelation_place' => 'Mekah', 'ayah_count' => 37],
            ['number' => 46, 'name_ar' => 'الأحقاف', 'name_id' => 'Al-Ahqaf', 'revelation_place' => 'Mekah', 'ayah_count' => 35],
            ['number' => 47, 'name_ar' => 'محمد', 'name_id' => 'Muhammad', 'revelation_place' => 'Madinah', 'ayah_count' => 38],
            ['number' => 48, 'name_ar' => 'الفتح', 'name_id' => 'Al-Fath', 'revelation_place' => 'Madinah', 'ayah_count' => 29],
            ['number' => 49, 'name_ar' => 'الحجرات', 'name_id' => 'Al-Hujurat', 'revelation_place' => 'Madinah', 'ayah_count' => 18],
            ['number' => 50, 'name_ar' => 'ق', 'name_id' => 'Qaf', 'revelation_place' => 'Mekah', 'ayah_count' => 45],
            ['number' => 51, 'name_ar' => 'الذاريات', 'name_id' => 'Adz-Dzariyat', 'revelation_place' => 'Mekah', 'ayah_count' => 60],
            ['number' => 52, 'name_ar' => 'الطور', 'name_id' => 'At-Tur', 'revelation_place' => 'Mekah', 'ayah_count' => 49],
            ['number' => 53, 'name_ar' => 'النجم', 'name_id' => 'An-Najm', 'revelation_place' => 'Mekah', 'ayah_count' => 62],
            ['number' => 54, 'name_ar' => 'القمر', 'name_id' => 'Al-Qamar', 'revelation_place' => 'Mekah', 'ayah_count' => 55],
            ['number' => 55, 'name_ar' => 'الرحمن', 'name_id' => 'Ar-Rahman', 'revelation_place' => 'Madinah', 'ayah_count' => 78],
            ['number' => 56, 'name_ar' => 'الواقعة', 'name_id' => 'Al-Waqi\'ah', 'revelation_place' => 'Mekah', 'ayah_count' => 96],
            ['number' => 57, 'name_ar' => 'الحديد', 'name_id' => 'Al-Hadid', 'revelation_place' => 'Madinah', 'ayah_count' => 29],
            ['number' => 58, 'name_ar' => 'المجادلة', 'name_id' => 'Al-Mujadilah', 'revelation_place' => 'Madinah', 'ayah_count' => 22],
            ['number' => 59, 'name_ar' => 'الحشر', 'name_id' => 'Al-Hasyr', 'revelation_place' => 'Madinah', 'ayah_count' => 24],
            ['number' => 60, 'name_ar' => 'الممتحنة', 'name_id' => 'Al-Mumtahanah', 'revelation_place' => 'Madinah', 'ayah_count' => 13],
            ['number' => 61, 'name_ar' => 'الصف', 'name_id' => 'Ash-Shaff', 'revelation_place' => 'Madinah', 'ayah_count' => 14],
            ['number' => 62, 'name_ar' => 'الجمعة', 'name_id' => 'Al-Jumu\'ah', 'revelation_place' => 'Madinah', 'ayah_count' => 11],
            ['number' => 63, 'name_ar' => 'المنافقون', 'name_id' => 'Al-Munafiqun', 'revelation_place' => 'Madinah', 'ayah_count' => 11],
            ['number' => 64, 'name_ar' => 'التغابن', 'name_id' => 'At-Taghabun', 'revelation_place' => 'Madinah', 'ayah_count' => 18],
            ['number' => 65, 'name_ar' => 'الطلاق', 'name_id' => 'At-Talaq', 'revelation_place' => 'Madinah', 'ayah_count' => 12],
            ['number' => 66, 'name_ar' => 'التحريم', 'name_id' => 'At-Tahrim', 'revelation_place' => 'Madinah', 'ayah_count' => 12],
            ['number' => 67, 'name_ar' => 'الملك', 'name_id' => 'Al-Mulk', 'revelation_place' => 'Mekah', 'ayah_count' => 30],
            ['number' => 68, 'name_ar' => 'القلم', 'name_id' => 'Al-Qalam', 'revelation_place' => 'Mekah', 'ayah_count' => 52],
            ['number' => 69, 'name_ar' => 'الحاقة', 'name_id' => 'Al-Haqqah', 'revelation_place' => 'Mekah', 'ayah_count' => 52],
            ['number' => 70, 'name_ar' => 'المعارج', 'name_id' => 'Al-Ma\'arij', 'revelation_place' => 'Mekah', 'ayah_count' => 44],
            ['number' => 71, 'name_ar' => 'نوح', 'name_id' => 'Nuh', 'revelation_place' => 'Mekah', 'ayah_count' => 28],
            ['number' => 72, 'name_ar' => 'الجن', 'name_id' => 'Al-Jinn', 'revelation_place' => 'Mekah', 'ayah_count' => 28],
            ['number' => 73, 'name_ar' => 'المزمل', 'name_id' => 'Al-Muzzammil', 'revelation_place' => 'Mekah', 'ayah_count' => 20],
            ['number' => 74, 'name_ar' => 'المدثر', 'name_id' => 'Al-Muddatstsir', 'revelation_place' => 'Mekah', 'ayah_count' => 56],
            ['number' => 75, 'name_ar' => 'القيامة', 'name_id' => 'Al-Qiyamah', 'revelation_place' => 'Mekah', 'ayah_count' => 40],
            ['number' => 76, 'name_ar' => 'الانسان', 'name_id' => 'Al-Insan', 'revelation_place' => 'Madinah', 'ayah_count' => 31],
            ['number' => 77, 'name_ar' => 'المرسلات', 'name_id' => 'Al-Mursalat', 'revelation_place' => 'Mekah', 'ayah_count' => 50],
            ['number' => 78, 'name_ar' => 'النبإ', 'name_id' => "An-Naba'", 'revelation_place' => 'Mekah', 'ayah_count' => 40],
            ['number' => 79, 'name_ar' => 'النازعات', 'name_id' => "An-Nazi'at", 'revelation_place' => 'Mekah', 'ayah_count' => 46],
            ['number' => 80, 'name_ar' => 'عبس', 'name_id' => 'Abasa', 'revelation_place' => 'Mekah', 'ayah_count' => 42],
            ['number' => 81, 'name_ar' => 'التكوير', 'name_id' => 'At-Takwir', 'revelation_place' => 'Mekah', 'ayah_count' => 29],
            ['number' => 82, 'name_ar' => 'الإنفطار', 'name_id' => 'Al-Infithar', 'revelation_place' => 'Mekah', 'ayah_count' => 19],
            ['number' => 83, 'name_ar' => 'المطففين', 'name_id' => 'Al-Muthaffifin', 'revelation_place' => 'Mekah', 'ayah_count' => 36],
            ['number' => 84, 'name_ar' => 'الإنشقاق', 'name_id' => 'Al-Insyiqaq', 'revelation_place' => 'Mekah', 'ayah_count' => 25],
            ['number' => 85, 'name_ar' => 'البروج', 'name_id' => 'Al-Buruj', 'revelation_place' => 'Mekah', 'ayah_count' => 22],
            ['number' => 86, 'name_ar' => 'الطارق', 'name_id' => 'At-Tariq', 'revelation_place' => 'Mekah', 'ayah_count' => 17],
            ['number' => 87, 'name_ar' => 'الأعلى', 'name_id' => "Al-A'la", 'revelation_place' => 'Mekah', 'ayah_count' => 19],
            ['number' => 88, 'name_ar' => 'الغاشية', 'name_id' => 'Al-Ghasyiyah', 'revelation_place' => 'Mekah', 'ayah_count' => 26],
            ['number' => 89, 'name_ar' => 'الفجر', 'name_id' => 'Al-Fajr', 'revelation_place' => 'Mekah', 'ayah_count' => 30],
            ['number' => 90, 'name_ar' => 'البلد', 'name_id' => 'Al-Balad', 'revelation_place' => 'Mekah', 'ayah_count' => 20],
            ['number' => 91, 'name_ar' => 'الشمس', 'name_id' => 'Asy-Syams', 'revelation_place' => 'Mekah', 'ayah_count' => 15],
            ['number' => 92, 'name_ar' => 'الليل', 'name_id' => 'Al-Lail', 'revelation_place' => 'Mekah', 'ayah_count' => 21],
            ['number' => 93, 'name_ar' => 'الضحى', 'name_id' => 'Ad-Duha', 'revelation_place' => 'Mekah', 'ayah_count' => 11],
            ['number' => 94, 'name_ar' => 'الشرح', 'name_id' => 'Asy-Syarh', 'revelation_place' => 'Mekah', 'ayah_count' => 8],
            ['number' => 95, 'name_ar' => 'التين', 'name_id' => 'At-Tin', 'revelation_place' => 'Mekah', 'ayah_count' => 8],
            ['number' => 96, 'name_ar' => 'العلق', 'name_id' => "Al-'Alaq", 'revelation_place' => 'Mekah', 'ayah_count' => 19],
            ['number' => 97, 'name_ar' => 'القدر', 'name_id' => 'Al-Qadr', 'revelation_place' => 'Mekah', 'ayah_count' => 5],
            ['number' => 98, 'name_ar' => 'البينة', 'name_id' => 'Al-Bayyinah', 'revelation_place' => 'Madinah', 'ayah_count' => 8],
            ['number' => 99, 'name_ar' => 'الزلزلة', 'name_id' => 'Az-Zalzalah', 'revelation_place' => 'Madinah', 'ayah_count' => 8],
            ['number' => 100, 'name_ar' => 'العاديات', 'name_id' => "Al-'Adiyat", 'revelation_place' => 'Mekah', 'ayah_count' => 11],
            ['number' => 101, 'name_ar' => 'القارعة', 'name_id' => "Al-Qari'ah", 'revelation_place' => 'Mekah', 'ayah_count' => 11],
            ['number' => 102, 'name_ar' => 'التكاثر', 'name_id' => 'At-Takasur', 'revelation_place' => 'Mekah', 'ayah_count' => 8],
            ['number' => 103, 'name_ar' => 'العصر', 'name_id' => "Al-'Asr", 'revelation_place' => 'Mekah', 'ayah_count' => 3],
            ['number' => 104, 'name_ar' => 'الهمزة', 'name_id' => 'Al-Humazah', 'revelation_place' => 'Mekah', 'ayah_count' => 9],
            ['number' => 105, 'name_ar' => 'الفيل', 'name_id' => 'Al-Fil', 'revelation_place' => 'Mekah', 'ayah_count' => 5],
            ['number' => 106, 'name_ar' => 'قريش', 'name_id' => 'Quraisy', 'revelation_place' => 'Mekah', 'ayah_count' => 4],
            ['number' => 107, 'name_ar' => 'الماعون', 'name_id' => "Al-Ma'un", 'revelation_place' => 'Mekah', 'ayah_count' => 7],
            ['number' => 108, 'name_ar' => 'الكوثر', 'name_id' => 'Al-Kausar', 'revelation_place' => 'Mekah', 'ayah_count' => 3],
            ['number' => 109, 'name_ar' => 'الكافرون', 'name_id' => 'Al-Kafirun', 'revelation_place' => 'Mekah', 'ayah_count' => 6],
            ['number' => 110, 'name_ar' => 'النصر', 'name_id' => 'An-Nasr', 'revelation_place' => 'Madinah', 'ayah_count' => 3],
            ['number' => 111, 'name_ar' => 'المسد', 'name_id' => 'Al-Lahab', 'revelation_place' => 'Mekah', 'ayah_count' => 5],
            ['number' => 112, 'name_ar' => 'الإخلاص', 'name_id' => 'Al-Ikhlas', 'revelation_place' => 'Mekah', 'ayah_count' => 4],
            ['number' => 113, 'name_ar' => 'الفلق', 'name_id' => 'Al-Falaq', 'revelation_place' => 'Mekah', 'ayah_count' => 5],
            ['number' => 114, 'name_ar' => 'الناس', 'name_id' => 'An-Nas', 'revelation_place' => 'Mekah', 'ayah_count' => 6],
        ];

        foreach ($surahs as $surah) {
            Surah::updateOrCreate(
                ['number' => $surah['number']],
                $surah
            );
        }
    }
}
